function arrayViewer(array,params)

figure;

set(gcf,'Color',params.bgColor);

hold on;

grid on;

axis equal;

xlabel('X (m)','Color','w');

ylabel('Y (m)','Color','w');

zlabel('Z (m)','Color','w');

title('Antenna Array Geometry','Color','w');

set(gca,'Color',params.bgColor);

scatter3(...
    array.positions(:,1),...
    array.positions(:,2),...
    array.positions(:,3),...
    300,...
    params.arrayColor,...
    'filled');

for i = 1:array.numElements

    text(...
        array.positions(i,1),...
        array.positions(i,2),...
        array.positions(i,3)+0.01,...
        array.labels{i},...
        'Color','w',...
        'FontSize',12);

end

plot3(...
    array.positions([1 2],1),...
    array.positions([1 2],2),...
    array.positions([1 2],3),...
    'w','LineWidth',2);

plot3(...
    array.positions([2 4],1),...
    array.positions([2 4],2),...
    array.positions([2 4],3),...
    'w','LineWidth',2);

plot3(...
    array.positions([4 3],1),...
    array.positions([4 3],2),...
    array.positions([4 3],3),...
    'w','LineWidth',2);

plot3(...
    array.positions([3 1],1),...
    array.positions([3 1],2),...
    array.positions([3 1],3),...
    'w','LineWidth',2);

scatter3(0,0,0,250,'white','filled');

text(0,0,0.01,...
    'CENTER',...
    'Color','white');

view(45,25);

end