function dashboardHUD(azEst,elEst,direction,params)

figure;

set(gcf,'Color',params.bgColor);

axis off;

hold on;

xlim([0 100]);

ylim([0 100]);

%% TITLE

text(50,...
95,...
'RF DIRECTION FINDING SYSTEM',...
'Color','white',...
'FontSize',18,...
'FontWeight','bold',...
'HorizontalAlignment','center');

plot([10 90],[88 88],...
'w',...
'LineWidth',1.5);

%% BEARING

text(20,78,...
'BEARING',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(20,72,...
sprintf('%.1f°',azEst),...
'Color',params.signalColor,...
'FontSize',22,...
'FontWeight','bold');

%% AZIMUTH

text(20,60,...
'AZIMUTH',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(20,54,...
sprintf('%.1f°',azEst),...
'Color',params.signalColor,...
'FontSize',22,...
'FontWeight','bold');

%% ELEVATION

text(20,42,...
'ELEVATION',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(20,36,...
sprintf('%.1f°',elEst),...
'Color',params.signalColor,...
'FontSize',22,...
'FontWeight','bold');

%% DIRECTION

text(20,24,...
'DIRECTION',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(20,18,...
direction,...
'Color',[0 1 0],...
'FontSize',20,...
'FontWeight','bold');

%% FREQUENCY

text(60,78,...
'FREQUENCY',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(60,72,...
sprintf('%.2f GHz',params.fc/1e9),...
'Color','white',...
'FontSize',18);

%% ELEMENTS

text(60,60,...
'ELEMENTS',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(60,54,...
sprintf('%d',params.numElements),...
'Color','white',...
'FontSize',18);

%% SNR

text(60,42,...
'SNR',...
'Color',[0.6 0.8 1],...
'FontSize',13);

text(60,36,...
sprintf('%.1f dB',params.SNR),...
'Color','white',...
'FontSize',18);

%% STATUS

rectangle(...
'Position',[30 5 40 8],...
'Curvature',0.2,...
'FaceColor',[0 0.5 0]);

text(50,...
9,...
'TRACKED',...
'Color','white',...
'FontSize',14,...
'FontWeight','bold',...
'HorizontalAlignment','center');

title('Operator Dashboard',...
'Color','white');

end