function elevationHUD(elevation,params)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% ELEVATION HUD
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

figure;

set(gcf,'Color',params.bgColor);

hold on;

axis equal;

axis off;

set(gca,'Color',params.bgColor);

plot([0 0],[0 90],...
    'Color',[0.7 0.7 0.7],...
    'LineWidth',2);

for k = 0:10:90

    plot([-0.05 0.05],[k k],...
        'Color',[0.5 0.5 0.5]);

    text(...
        0.1,...
        k,...
        sprintf('%d°',k),...
        'Color','white');

end

scatter(...
    0,...
    elevation,...
    250,...
    params.signalColor,...
    'filled');

plot([0 0],...
    [0 elevation],...
    'Color',params.signalColor,...
    'LineWidth',3);

title(...
    'Elevation HUD',...
    'Color','white');

text(...
    0,...
    -10,...
    sprintf('Elevation : %.1f°',elevation),...
    'Color','white',...
    'FontSize',13,...
    'HorizontalAlignment','center');

xlim([-1 1]);

ylim([-15 95]);

end