%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RF DIRECTION FINDING SIMULATOR
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clc;
close all;
clear;

addpath(genpath(pwd));

disp(' ');
disp('======================================');
disp('RF DIRECTION FINDING SIMULATOR');
disp('======================================');
disp(' ');

%% CONFIGURATION

params = config();

%% SCENARIO

scenario = scenarioGenerator(params);

%% ARRAY GEOMETRY

array = arrayGeometry(params);

%% STEERING VECTOR

a = steeringVector( ...
        array,...
        scenario.azimuth,...
        scenario.elevation,...
        params);

%% SIGNAL GENERATION

X = signalGenerator( ...
        array,...
        scenario,...
        params);

%% COVARIANCE MATRIX

R = covarianceMatrix(X);

%% MUSIC ALGORITHM

[Pmusic,AZ,EL] = music2D( ...
                    R,...
                    array,...
                    params);

%% PEAK DETECTION

[azEst,elEst] = peakEstimator( ...
                    Pmusic,...
                    AZ,...
                    EL);

%% DIRECTION ESTIMATION

direction = directionEstimator(azEst);

%% RESULTS

disp(' ');
disp('======================================');

fprintf('Bearing   : %.2f deg\n',azEst);

fprintf('Azimuth   : %.2f deg\n',azEst);

fprintf('Elevation : %.2f deg\n',elEst);

fprintf('Direction : %s\n',direction);

disp('======================================');
disp(' ');

%% VISUALIZATION

rfScene3D( ...
        array,...
        azEst,...
        elEst,...
        params);

arrayViewer( ...
        array,...
        params);

wavefrontAnimation( ...
        array,...
        azEst,...
        elEst,...
        params);

compassHUD( ...
        azEst,...
        params);

elevationHUD( ...
        elEst,...
        params);

musicViewer( ...
        Pmusic,...
        AZ,...
        EL,...
        azEst,...
        elEst,...
        params);

phaseViewer( ...
        a,...
        array,...
        params);

dashboardHUD( ...
        azEst,...
        elEst,...
        direction,...
        params);

disp(' ');
disp('======================================');
disp('SIMULATION COMPLETE');
disp('======================================');
disp(' ');