function phaseViewer(a,array,params)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% PHASE VIEWER
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

figure;

set(gcf,'Color',params.bgColor);

hold on;

axis equal;

axis off;

set(gca,'Color',params.bgColor);

phaseDeg = angle(a);

phaseDeg = rad2deg(phaseDeg);

scatter(...
    array.positions(:,1),...
    array.positions(:,2),...
    300,...
    phaseDeg,...
    'filled');

colormap(jet);

colorbar;

for i=1:array.numElements

    text(...
        array.positions(i,1),...
        array.positions(i,2)+0.01,...
        sprintf('%s\n%.1f°',...
        array.labels{i},...
        phaseDeg(i)),...
        'Color','white',...
        'HorizontalAlignment','center');

end

scatter(0,0,...
    200,...
    'w',...
    'filled');

text(...
    0,...
    0.015,...
    'CENTER',...
    'Color','white',...
    'HorizontalAlignment','center');

title(...
    'Array Phase Distribution',...
    'Color','white');

end